package com.intuit.craftdemo.enums;

public enum DriverStatus {
    APPLICATION_SUBMITTED, ALL_DOCUMENTS_SUBMITTED, DOCUMENTATION_VERIFICATION_FAILED, DOCUMENTS_VERIFIED, BACKGROUND_CHECK_COMPLETED,
    BACKGROUND_CHECK_FAILED, READY_TO_DRIVE
}
